#Spring Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: changeme
    url: jdbc:postgresql://localhost:5432/plant-library?currentSchema=${spring.jpa.properties.hibernate.default_schema}
    username: changeme
    hikari:
      # The maximum amount of time during which a connection can be idle in the pool
      idleTimeout: 600000
      # Will attempt to maintain a connection to prevent a database or network infrastructure timeout.
      keepaliveTime: 0
      # This property controls the maximum lifetime of a connection in the pool.
      maxLifetime: 1800000
      # This property defines the minimum number of idle connections that HikariCP tries to maintain in the pool.
      minimumIdle: 10
      # This property controls the maximum size that the pool can reach, including idle and used connections.
      maximumPoolSize: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: plant
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  cloud:
    openfeign:
      lazy-attributes-resolution: true

#Logging configuration
logging:
  level:
    com:
      auth: ${logging-level}
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){cyan} %highlight(${LOG_LEVEL_PATTERN:-%6p}) %clr(:){faint} %green(%X{requestId}) %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
logging-level: DEBUG

#Server configuration
server:
  port: 8081
  servlet:
    context-path: /plant

#Springdoc configuration
springdoc:
  swagger-ui:
    default-models-expand-depth: -1
    disable-swagger-default-url: true
  api-docs:
    enabled: true
  packages-to-scan: com.plant.api.controller